// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Rldt2zGXn4f0ygsszsjINcv6pWcSMm8',
    appId: '1:764426020328:web:76c6f300121ca181b5705d',
    messagingSenderId: '764426020328',
    projectId: 'chat-f85c3',
    authDomain: 'chat-f85c3.firebaseapp.com',
    storageBucket: 'chat-f85c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEsqSEUqMx1b4XdpFpWCMR_iSwv3GSYz4',
    appId: '1:764426020328:android:34d94dc46443a315b5705d',
    messagingSenderId: '764426020328',
    projectId: 'chat-f85c3',
    storageBucket: 'chat-f85c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH2wCy-n-b0AV1NOc3Uz89kbbyef9HNBw',
    appId: '1:764426020328:ios:31021ea296458f4cb5705d',
    messagingSenderId: '764426020328',
    projectId: 'chat-f85c3',
    storageBucket: 'chat-f85c3.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH2wCy-n-b0AV1NOc3Uz89kbbyef9HNBw',
    appId: '1:764426020328:ios:31021ea296458f4cb5705d',
    messagingSenderId: '764426020328',
    projectId: 'chat-f85c3',
    storageBucket: 'chat-f85c3.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Rldt2zGXn4f0ygsszsjINcv6pWcSMm8',
    appId: '1:764426020328:web:f5d1376222f03392b5705d',
    messagingSenderId: '764426020328',
    projectId: 'chat-f85c3',
    authDomain: 'chat-f85c3.firebaseapp.com',
    storageBucket: 'chat-f85c3.appspot.com',
  );

}